//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Cancels = new HashSet<Cancel>();
        }
    
        public string Bid { get; set; }
        public Nullable<int> Tno { get; set; }
        public string @class { get; set; }
        public Nullable<System.DateTime> Bdate { get; set; }
        public Nullable<System.DateTime> Travdate { get; set; }
        public Nullable<int> NoofTic { get; set; }
        public Nullable<int> TotalAmt { get; set; }
    
        public virtual TrainDetail TrainDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancel> Cancels { get; set; }
    }
}
