//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancel
    {
        public string Cid { get; set; }
        public Nullable<System.DateTime> Candate { get; set; }
        public Nullable<int> Tno { get; set; }
        public Nullable<int> NoofCTic { get; set; }
        public Nullable<int> refund { get; set; }
        public string rem { get; set; }
        public string Bid { get; set; }
        public string @class { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual TrainDetail TrainDetail { get; set; }
    }
}
